"""Подписи действий журнала — по-русски, для человека (владелец, 24.09.2026).

Журнал показывал сырые ключи вида `patch_sales_deal`: подписана была 71 запись из 266
действий в коде. Здесь — все. Новое действие без подписи роняет
`tests/test_audit_labels.py`: ключ видит разработчик, а не человек в журнале.
"""

ACTION_LABELS = {
    # Приложения к договору (05–06.09.2026) и демо-стенд DSP. Без подписи журнал
    # показывает сырой ключ вида `annex_confirm` — строка есть, а прочесть её нельзя.
    "annex_create": "Черновик приложения к договору",
    "annex_edit": "Черновик приложения изменён",
    "annex_confirm": "Приложение к договору выпущено",
    "annex_start_no": "Стартовый номер приложений по договору",
    "annex_template_create": "Формулировка услуги заведена",
    "annex_template_edit": "Формулировка услуги изменена",
    # Админка трафика (каталог блоков) — тоже без подписей до 06.09.2026.
    "traffic_catalog_code_edit": "Код площадки изменён",
    "traffic_catalog_surface_add": "Поверхность площадки добавлена",
    "traffic_catalog_surface_edit": "Поверхность площадки изменена",
    "traffic_catalog_block_add": "Рекламный блок добавлен",
    "traffic_catalog_block_edit": "Рекламный блок изменён",
    "traffic_catalog_block_delete": "Рекламный блок удалён",
    "counterparty_signer": "Подписант контрагента",
    "traffic_creative_script": "Скрипт, вшиваемый в креатив",
    "import_apply": "Импорт операций из файла",
    "ord_resolve_submission": "Разбор зависшей отправки в ОРД",
    "weborama_provision": "Пиксели Weborama по РК",
    "dsp_provision": "Выгрузка креативов РК в DSP",
    "external_resolve": "Сверка с кабинетом DSP/Weborama после попытки без ответа",
    "dsp_demo_campaign": "DSP демо: кампания заведена",
    "dsp_demo_creative": "DSP демо: креатив заведён",
    "dsp_demo_status": "DSP демо: статус кампании",
    "dsp_demo_plan": "DSP демо: план кампании",
    "dsp_demo_targeting": "DSP демо: таргетинг",
    "verify_media_plan": "МП проверен",
    "traffic_dashboard_sync": "Обновление РК из сделок",
    "deal_weborama_pixel": "Доп. параметр РК: пиксель Weborama",
    "deal_verifier_shows": "Ручные показы Weborama на сверке",
    "cabinet_notify_toggle": "Рассылка площадкам: вид включён или выключен",
    "cabinet_delete": "Кабинет площадки удалён",
    "cabinet_notify_hours": "Рассылка площадкам: тихие часы и час дайджеста",
    "targeting_link": "Ссылка нацеливания выпущена",
    "mail_settings": "Настройки почты изменены",
    "mail_shell": "Правка оболочки письма",
    "mail_card_text": "Правка текста карточки уведомления",
    "mail_template": "Шаблон письма изменён",
    "mail_test": "Проверочное письмо отправлено",
    "ord_sync_kktu": "Заливка справочника ККТУ из ОРД",
    "upload_deal_brief_file": "Файл прикреплён к брифу сделки",
    "delete_deal_brief_file": "Файл брифа снят",
    "ord_link_final": "Доходный ОРД привязан к нашему договору",
    "ord_defer_final": "Доходный ОРД отложен на разбор",
    "ord_reopen_final": "Доходный ОРД возвращён на разбор",
    "set_advertiser_sales_rep": "Ответственный сейлз рекламодателя",
    "ord_initial_delete": "Чистка зеркала: удаление изначальных договоров",
    "bug_report_new": "Заявка о сбое принята",
    "bug_report_status": "Заявка о сбое: смена статуса",
    "bug_report_backlog": "Из заявки заведено наблюдение",
    "maintenance_on": "Объявлено техобслуживание",
    "maintenance_off": "Техобслуживание снято",
    "ord_sync_clients": "Сверка юрлиц с ОРД",
    "ord_sync_contracts": "Сверка договоров с ОРД",
    "ord_register_final": "Договор зарегистрирован в ОРД",
    "ord_register_initial": "Изначальный договор заведён в ОРД",
    "ord_attach_initial": "Изначальный прикреплён к доходному",
    "self_promo_on": "Присвоен статус «самореклама»",
    "self_promo_off": "Снят статус «самореклама»",
    "media_plan_change_note": "Причина изменений МП",
    "deal_title_from_mp": "Название сделки из медиаплана",
    "login_success": "Вход выполнен",
    "login_failed": "Неудачный вход",
    "create_user": "Создание пользователя",
    "update_user": "Изменение пользователя",
    "delete_user": "Удаление пользователя",
    "create_operation": "Создание операции",
    "update_operation": "Изменение операции",
    "delete_operation": "Удаление операции",
    # Цепочки частичных оплат и фиксация МП на «Сборке» (23.09.2026).
    "partial_payment_operation": "Частичная оплата операции",
    "unlink_operation_parent": "Отвязка частичной оплаты",
    "force_delete_operation": "Принудительное удаление операции (с паролем)",
    "media_plan_locked_edit": "Правка зафиксированного медиаплана мастером",
    "create_role": "Создание роли",
    "update_role": "Изменение роли",
    "delete_role": "Удаление роли",
    "update_counterparty": "Изменение контрагента",
    "delete_counterparty": "Удаление контрагента",
    "bulk_update_counterparty": "Массовое изменение контрагентов",
    # ── дописано 24.09.2026: всё, что журнал показывал сырым ключом ──
    "create_deal": "Сделка создана",
    "patch_sales_deal": "Сделка изменена",
    "bulk_update_deals": "Массовая правка сделок",
    "bulk_delete_deals": "Сделки удалены",
    "move_deal": "Сделка переведена на другую стадию",
    "add_deal_comment": "Комментарий к сделке",
    "save_deal_brief": "Бриф сделки сохранён",
    "save_deal_brief_mp": "Бриф сделки сохранён из медиаплана",
    "save_deal_traffic_brief": "Бриф трафика сделки сохранён",
    "upload_deal_file": "Файл прикреплён к сделке",
    "delete_deal_file": "Файл сделки удалён",
    "drop_sales_override": "Снята ручная правка поля сделки",
    "apply_brand_suggestions": "Бренды сделок подставлены по подсказкам",
    "snooze_deal": "Сделка отложена",
    "unsnooze_deal": "Сделка возвращена из отложенных",
    "prolong_deal": "РК продлена копией сделки",
    "push_deal_to_bitrix": "Сделка отправлена в Битрикс",
    "push_edits_to_bitrix": "Правки сделки отправлены в Битрикс",
    "sync_deal_from_bitrix": "Сделка обновлена из Битрикса",
    "sync_bulk_from_bitrix": "Сделки обновлены из Битрикса",
    "create_media_plan": "Медиаплан создан",
    "update_media_plan": "Медиаплан изменён",
    "patch_media_plan": "Медиаплан изменён",
    "delete_media_plan": "Медиаплан удалён",
    "submit_media_plan": "Медиаплан отправлен",
    "mp_status_rejected": "Медиаплан отклонён",
    "link_deal_media_plan": "Медиаплан привязан к сделке",
    "create_deal_from_media_plan": "Сделка создана из медиаплана",
    "deal_from_mp": "Сделка обновлена из медиаплана",
    "year_plan_create": "Годовой план создан",
    "year_plan_update": "Годовой план изменён",
    "year_plan_save": "Годовой план сохранён",
    "year_plan_delete": "Годовой план удалён",
    "year_plan_attach_deal": "Сделка привязана к строке годового плана",
    "year_plan_detach_deal": "Сделка отвязана от строки годового плана",
    "year_plan_create_deals": "Сделки созданы из годового плана",
    "year_plan_match_deals": "Сверка годового плана со сделками",
    "year_plan_export": "Годовой медиаплан выгружен в Excel",
    "create_creative_set": "Комплект креативов заведён",
    "send_creative_set": "Комплект креативов отправлен трафику",
    "primary_creative_review": "Первичное согласование креатива",
    "creative_pair_verdict": "Решение площадки по креативу",
    "traffic_pair_verdict": "Решение трафика по паре",
    "traffic_pair_file": "Скриншот размещения приложен",
    "delete_pair_file": "Скриншот размещения удалён",
    "add_creative_targets": "Площадки добавлены к комплекту",
    "auto_creative_targets": "Площадки комплекта подставлены автоматически",
    "move_creative_target": "Площадка перенесена в другой комплект",
    "issue_erid": "ЕРИД выпущен",
    "set_foreign_erid": "Внесён чужой ЕРИД",
    "rights_letter_upload": "Письмо о правах приложено",
    "rights_letter_delete": "Письмо о правах удалено",
    "request_target_url": "Запрошена посадочная у площадки",
    "set_target_url": "Посадочная ссылка указана",
    "set_traffic_manager": "Назначен ответственный трафика",
    "ad_campaign_status": "Статус РК изменён",
    "ad_campaign_finish": "РК завершена",
    "ad_placement_status": "Статус размещения изменён",
    "ad_creative_status": "Статус креатива изменён",
    "weborama_stats_pull": "Статистика Weborama снята",
    "balancer_import": "Балансировщик: загружен файл",
    "balancer_recalc": "Балансировщик: пересчёт",
    "balancer_row_edit": "Балансировщик: правка строки",
    "balancer_settings": "Балансировщик: настройки",
    "weborama_login": "Weborama демо: вход",
    "weborama_project": "Weborama демо: проект",
    "weborama_campaign": "Weborama демо: кампания",
    "weborama_ad_network": "Weborama демо: рекламная сеть",
    "weborama_insertion": "Weborama демо: вставка",
    "ord_import": "Загрузка выгрузки ОРД из файла",
    "ord_create_final": "Доходный договор заведён в ОРД",
    "ord_create_initial": "Изначальный договор заведён",
    "ord_create_payer": "Юрлицо плательщика заведено в ОРД",
    "ord_set_final": "Доходный договор ОРД выбран для сделки",
    "ord_set_payer": "Плательщик выбран для сделки",
    "ord_bind_initial_forced": "Изначальный привязан к сделке вручную",
    "create_contract": "Договор создан",
    "update_contract": "Договор изменён",
    "delete_contract": "Договор удалён",
    "bulk_update_contract": "Массовая правка договоров",
    "bulk_delete_contract": "Договоры удалены",
    "import_update_contract": "Договор обновлён из файла",
    "upload_contract_document": "Скан договора приложен",
    "delete_contract_document": "Скан договора удалён",
    "create_counterparty": "Контрагент создан",
    "bulk_delete_counterparty": "Контрагенты удалены",
    "update_counterparty_defaults": "Умолчания контрагента изменены",
    "update_counterparty_requisites": "Реквизиты контрагента изменены",
    "update_counterparty_note": "Примечание к дебиторке",
    "update_bank_balance": "Стартовый остаток банка изменён",
    "bulk_update_operation": "Массовая правка операций",
    "bulk_delete_operation": "Операции удалены",
    "upload_operation_file": "Скан приложен к операции",
    "delete_operation_file": "Скан операции удалён",
    "export_alfa": "Платёжки выгружены в Альфа-Банк",
    "diadoc_import": "Документы Диадока загружены",
    "diadoc_unlink": "Документ Диадока отвязан от операции",
    "create_sales_advertiser": "Рекламодатель создан",
    "update_sales_advertiser": "Рекламодатель изменён",
    "deactivate_sales_advertiser": "Рекламодатель в архиве",
    "restore_sales_advertiser": "Рекламодатель возвращён из архива",
    "merge_advertiser": "Рекламодатели объединены",
    "create_sales_agency": "Агентство создано",
    "update_sales_agency": "Агентство изменено",
    "deactivate_sales_agency": "Агентство в архиве",
    "restore_sales_agency": "Агентство возвращено из архива",
    "merge_agency": "Агентства объединены",
    "split_agency_omd": "Агентство разделено",
    "set_agency_sk": "СК агентства изменена",
    "create_sales_brand": "Бренд создан",
    "update_sales_brand": "Бренд изменён",
    "deactivate_sales_brand": "Бренд в архиве",
    "delete_brand_hard": "Бренд удалён",
    "merge_brands": "Бренды объединены",
    "move_brands": "Бренды перенесены к другому рекламодателю",
    "set_brand_marking": "Маркировка бренда изменена",
    "attach_agency_cp": "Юрлицо привязано к агентству",
    "detach_agency_cp": "Юрлицо отвязано от агентства",
    "attach_producer_cp": "Юрлицо привязано к рекламодателю",
    "detach_producer_cp": "Юрлицо отвязано от рекламодателя",
    "create_sales_service": "Услуга создана",
    "update_sales_service": "Услуга изменена",
    "deactivate_sales_service": "Услуга в архиве",
    "delete_sales_service": "Услуга удалена",
    "reorder_sales_services": "Порядок услуг изменён",
    "create_sales_service_group": "Группа услуг создана",
    "set_service_use": "Применение услуги изменено",
    "refresh_services": "Услуги обновлены из Битрикса",
    "create_sales_price": "Цена добавлена",
    "update_sales_price": "Цена изменена",
    "deactivate_sales_price": "Цена в архиве",
    "create_sales_format": "Формат создан",
    "update_sales_format": "Формат изменён",
    "delete_sales_format": "Формат удалён",
    "create_sales_addon": "Доп. услуга создана",
    "update_sales_addon": "Доп. услуга изменена",
    "delete_sales_addon": "Доп. услуга удалена",
    "create_geo": "География добавлена",
    "create_targeting_item": "Параметр таргетинга добавлен",
    "delete_targeting_item": "Параметр таргетинга удалён",
    "refresh_pipelines": "Воронки обновлены из Битрикса",
    "rename_pipeline": "Воронка переименована",
    "delete_sales_pipeline": "Воронка удалена",
    "set_pipeline_tracked": "Воронка включена или выключена",
    "map_stage": "Стадия Битрикса сопоставлена с нашей",
    "unmap_stage": "Сопоставление стадии снято",
    "save_stage_catalog": "Каталог стадий сохранён",
    "bx_link": "Связь с Битриксом установлена",
    "bx_link_many": "Связи с Битриксом установлены пачкой",
    "bx_auto_link": "Связи с Битриксом подобраны автоматически",
    "bx_unlink": "Связь с Битриксом снята",
    "bx_rename": "Название взято из Битрикса",
    "bx_import": "Запись загружена из Битрикса",
    "bx_import_many": "Записи загружены из Битрикса",
    "bx_import_deals": "Сделки загружены из Битрикса",
    "bx_create_company": "Компания заведена в Битриксе",
    "bx_flag_create": "Помечено к заведению в Битриксе",
    "bx_consolidate": "Дубли объединены по Битриксу",
    "bx_set_master": "Выбрана основная запись",
    "bx_delete_retired": "Удалены записи, выбывшие из Битрикса",
    "bx_sync_batch": "Пакетная сверка с Битриксом",
    "create_publisher": "Площадка создана",
    "patch_publisher": "Площадка изменена",
    "set_publisher_surface": "Поверхность площадки изменена",
    "delete_publisher_surface": "Поверхность площадки удалена",
    "set_publisher_platform": "Платформа площадки изменена",
    "set_publisher_service": "Услуга площадки изменена",
    "set_publisher_traffic": "Трафик площадки изменён",
    "add_publisher_contact": "Контакт площадки добавлен",
    "update_publisher_contact": "Контакт площадки изменён",
    "delete_publisher_contact": "Контакт площадки удалён",
    "attach_publisher_cp": "Юрлицо привязано к площадке",
    "detach_publisher_cp": "Юрлицо отвязано от площадки",
    "attach_publisher_contract": "Договор привязан к площадке",
    "detach_publisher_contract": "Договор отвязан от площадки",
    "archive_publisher_contract": "Договор площадки в архиве",
    "set_publisher_contract_edo": "Статус ЭДО договора площадки",
    "upload_publisher_contract_doc": "Скан договора площадки приложен",
    "upload_publisher_document": "Документ площадки приложен",
    "delete_publisher_document": "Документ площадки удалён",
    "create_publisher_kind": "Вид паблишера добавлен",
    "create_contact_position": "Должность контакта добавлена",
    "cabinet_create": "Кабинет площадки создан",
    "cabinet_update": "Кабинет площадки изменён",
    "cabinet_publishers": "Площадки кабинета изменены",
    "cabinet_access_grant": "Доступ в кабинет выдан",
    "cabinet_account_update": "Учётка кабинета изменена",
    "cabinet_account_password": "Пароль учётки кабинета выдан",
    "cabinet_chats": "Рабочие чаты кабинета изменены",
    "cabinet_our_contacts": "Наши контакты для площадок изменены",
    "consent_accepted": "Принято согласие на обработку персональных данных",
    "create_notification_profile": "Профиль уведомлений создан",
    "delete_notification_profile": "Профиль уведомлений удалён",
    "save_notification_profile_subs": "Подписки профиля уведомлений сохранены",
    "notify_event_test": "Проверочное уведомление отправлено",
    "backlog_create": "Бэклог отладки: запись заведена",
    "backlog_update": "Бэклог отладки: запись изменена",
    "backlog_status": "Бэклог отладки: смена статуса",
    "backlog_note": "Бэклог отладки: заметка",
}
